### ISSUE TITLE
FullRow editing in a grouped grid

### ISSUE THREAD

**Issue by Nevergonnachange** [ceolter/ag-grid-enterprise#102]
Hello,

I have a grouped grid (using getNodeChildDetails) and full-width row's (similar to grid-master-detail example in documentation).

Now I am trying to make the "non-detail" row's  (master-grid) editable. But it does not work. If I remove the getNodeChildDetails grid setting the editing is working as intended. When I add it again, no editing is possible.

Thanks in advance
Robin Gruschke

**Comment by ceolter** [comment]
new property in latest version ```enableGroupEdit```, set to true, groups will be editable
