### ISSUE TITLE
[clipboard] Unable to copy large amount of cells with keyboard

### ISSUE THREAD

**Issue by jgrenat** [ceolter/ag-grid-enterprise#103]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When selecting a range including many cells in the examples of the website, and using Ctrl+C, these cells are not copied as they should be. With a small number of cells, it works. No error in the console.

(Using the context menu, it still works properly)

**Expected behavior**
Ctrl + C should copy the cells

**Minimal reproduction of the problem with instructions**
Select a range with many cells on the [demo page](https://www.ag-grid.com/example.php) and try to copy with Ctrl + C

**Please tell us about your environment:** Windows 8

* **ag-Grid-Enterprise version:** 2.0.X

* **Browser:** Chrome 53

* **Language:** Not relevant

**Comment by seanlandsman** [comment]
Thanks for reporting - I've added this to our backlog (https://www.ag-grid.com/ag-grid-pipeline/) as issue AG-208

**Comment by ceolter** [comment]
fixed. will be in next release.

**Comment by jgrenat** [comment]
Thanks!
