### ISSUE TITLE
RichSelect dynamic values

### ISSUE THREAD

**Issue by razvanip** [ceolter/ag-grid-enterprise#108]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-ng2/blob/master/CONTRIBUTING.md#question
```

Hello, is it possible to have support for dynamic values on the richSelect component so that we can have different values of the same column type on different4 cells ?

**Comment by willhalling** [comment]
Hi @razvanip, I've raised this feature request with core dev team. You can track progress on our pipeline page (AG-243):

https://www.ag-grid.com/ag-grid-pipeline/

**Comment by razvanip** [comment]
@willhalling thanks

**Comment by chadbr** [comment]
@willhalling any word on this one? I don't see it here anymore: https://www.ag-grid.com/ag-grid-pipeline/

**Comment by seanlandsman** [comment]
Hi

We've declined this feature request - you can provide the values up from per cell.

If you're an enterprise customer please raise a support query on our Members Forum where we can assist you further: https://ag-grid.com/forum/forumdisplay.php?fid=5

thanks
