### ISSUE TITLE
can i call getColumnState() in constructor (or) onInit (or) when ever column position changes

### ISSUE THREAD

**Issue by nunna-suma** [ceolter/ag-grid-enterprise#111]
**I'm submitting a http://stackoverflow.com/questions/42295461/dispaly-info-about-columnvisible-columnpinned-columnresized-columnmoved-in-ag**  
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**
**http://stackoverflow.com/questions/42295461/dispaly-info-about-columnvisible-columnpinned-columnresized-columnmoved-in-ag can u please help me to solve these one

for eg: https://www.ag-grid.com/javascript-grid-column-api/columnStateExample.html 
in these example after clik the button getColumnState() but i'm trying to do whenever columns have changed like column moved, column pinned, column resized then it has to store the changes by using these one getColumnState() 
**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by willhalling** [comment]
Hello @nunna-suma,

If you're an enterprise customer please post support requests in the forum: 

https://www.ag-grid.com/forum/
