### ISSUE TITLE
Usage of ag-grid-enterprise in angular 2.4

### ISSUE THREAD

**Issue by AngularTx** [ceolter/ag-grid-enterprise#112]
We would like to use the ag-grid-enterprise package in our application. 

I would like to know what all packages would be required for installation for angular 2.4.0 version.

As of now we have installed packaged ag-grid , ag-grid-angular, and ag-grid-enterprise . The application is working fine . Do we need to have these 3 packages installed  to make the application run?

**Comment by seanlandsman** [comment]
You only need the enterprise package if you're making use of enterprise features, and if you have a valid enterprise license.

If you're only using the free version of ag-grid, then you need both ag-grid and ag-grid-angular

thanks

**Comment by ghetal** [comment]
even I want to use ag-grid-enterprise with my licensed version. So, what are the commands for installing ag-grid in angular 2? Also, tell me what other settings need to be done?

**Comment by seanlandsman** [comment]
Hi @ghetal - if you're an enterprise customer can you please use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

Once you register on the forum let accounts@ag-grid.com know your username and we'll grant access

We'll be able to assist you further with your request further there - thanks

**Comment by ghetal** [comment]
Ok thank you for information. my grid worked
