### ISSUE TITLE
Override Ag-grid Css Classes.

### ISSUE THREAD

**Issue by protagonist51** [ceolter/ag-grid-enterprise#113]
Hi,

We have our application built on Angular 2.4.8 with webpack. 

We are using the trial version of ag-grid enterprise. We would like to override the CSS classes so that we can change the interface as per our design. 

We are not able to override the  classes . Could you please provide some information on this topic?

**Comment by seanlandsman** [comment]
Hi - can you please lodge this support request in our Members Forum https://ag-grid.com/forum/forumdisplay.php?fid=5 where we'll be able to assist you further.

If you don't access please contact accounts@ag-grid.com first where they'll be able to give you access.

In the meantime, take a look at themes https://www.ag-grid.com/javascript-grid-styling - these are how look and feel of the grid can be changed at a high level
