### ISSUE TITLE
Get data when adding col

### ISSUE THREAD

**Issue by alhweiti** [ceolter/ag-grid-enterprise#114]
Hi,
we implemented ag-grid-enterprise in one of our solutions, we have more than one thousand columns.
So, to improve performance, we're looking into possibly loading only selected columns data, and then load other columns and bind data to the grid when user choose to add them to the grid. **Is that possible?** 
I looked and couldn't find API call for binding single column data to the grid?
Currently, there is setRowData(data) method but there is nothing like setColumnData(data)  to be able to set data upon selecting the desired column.

Thank you,

Ahlam

**Comment by seanlandsman** [comment]
Hi Ahlam,

Can you please raise this request in the Members Forum: https://ag-grid.com/forum/forumdisplay.php?fid=5 where one of the team will be able to assist you further.

GitHub is reserved for raising of issues or bugs, or possibly feature requests. Support queries should go through the forum instead please.

thanks
