### ISSUE TITLE
textFilter multiple input fail

### ISSUE THREAD

**Issue by liyuqi** [ceolter/ag-grid-enterprise#115]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

    __________________
    | filterType     |
    | filterText     |
    | filterType2    |
    | filterText2    |
    | Apply Filter   |
    __________________
1. create multiple textFilter input ex: [CONTAINS] filterText AND [NOT CONTAIN] filterText2

2. but both filterType2 and filterText are **undefined** after click [APPLY FILTER]

**Expected behavior**

1. create multiple textFilter and input like Excel data analysis

2. perform logical textFilter instead of using RegExp textFilter

**Minimal reproduction of the problem with instructions**

default.html
`    

    agGrid.TextFilter.prototype.createTemplate = function () {
    	var template = '<div>' +
        '<div>' +
	    '<select class="ag-filter-select" id="filterType">' +
	    '<option value="1">[CONTAINS]</option>' +
	    '<option value="2">[EQUALS]</option>' +
	    '<option value="3">[NOT EQUALS]</option>' +
	    '<option value="4">[STARTS WITH]</option>' +
	    '<option value="5">[ENDS WITH]</option>' +
	    '<option value="6">[NOT CONTAIN]</option>' +
	    '<option value="7">[NOT START WITH]</option>' +
	    '</select>' +
	    '</div>' +
	    '<div>' +
	    '<input class="ag-filter-filter" id="filterText" type="text" placeholder="[FILTER...]"/>' +
	    '</div>' +

	    '<div>' +
	    '<select class="ag-filter-select" id="filterType2">' +
	    '<option value="1">[CONTAINS]</option>' +
	    '<option value="2">[EQUALS]</option>' +
	    '<option value="3">[NOT EQUALS]</option>' +
	    '<option value="4">[STARTS WITH]</option>' +
	    '<option value="5">[ENDS WITH]</option>' +
	    '<option value="6">[NOT CONTAIN]</option>' +
	    '<option value="7">[NOT START WITH]</option>' +
	    '</select>' +
	    '</div>' +
	    '<div>' +
	    '<input class="ag-filter-filter" id="filterText2" type="text" placeholder="[FILTER...]"/>' +
	    '</div>' +
	    '<div class="ag-filter-apply-panel" id="applyPanel">' +
	    '<button type="button" id="applyButton">[APPLY FILTER]</button>' +
	    '</div>' +
	    '</div>';
        //this.filterType2 = this.gui.querySelector('#filterType2');
        //this.filterText2 = this.gui.querySelector('#filterText2');
        return template
};

`
`

    agGrid.TextFilter.prototype.doesFilterPass = function (node) {
        var value = this.valueGetter(node);
        if (!value) {
            return false;
        }
        
        var valueLowerCase = value.toString().toLowerCase();
  
        function filter2(valueLowerCase,filterType,filterText){
            var CONTAINS = 1;
            var EQUALS = 2;
            var NOT_EQUALS = 3;
            var STARTS_WITH = 4;
            var ENDS_WITH = 5;
            var NOT_CONTAIN = 6;
            var NOT_START_WITH = 7;
            if (!filterText) {
                return true;
            }
            switch (filterType) {
                case CONTAINS:
                    return valueLowerCase.indexOf(filterText) >= 0;
                case EQUALS:
                    return valueLowerCase === filterText;
                case NOT_EQUALS:
                    return valueLowerCase != filterText;
                case STARTS_WITH:
                    return valueLowerCase.indexOf(filterText) === 0;
                case ENDS_WITH:
                    var index = valueLowerCase.lastIndexOf(filterText);
                    return index >= 0 && index === (valueLowerCase.length - filterText.length);
                case NOT_CONTAIN:
                    return valueLowerCase.indexOf(filterText) < 0;
                case NOT_START_WITH:
                    return valueLowerCase.indexOf(filterText) !== 0;
                default:
                    // should never happen
                    console.warn('invalid filter type ' + filterType);
                    return false;
            }
        }

       console.log(valueLowerCase
               +'\t:'+this.filterType  +'-'+this.filterText +':'+filter2(valueLowerCase,this.filterType,this.filterText)
               +'\t,'+this.filterType2 +'-'+this.filterText2+':'+filter2(valueLowerCase,this.filterType2,this.filterText2));

       //JSON.stringify(node);
        return (filter2(valueLowerCase,this.filterType,this.filterText)
            && filter2(valueLowerCase,this.filterType2,this.filterText2))
	};

`

**What is the motivation / use case for changing the behavior?**

textFilter multiple input that perform logical textFilter intersection similar to Excel function 

**Please tell us about your environment:**

Ubuntu14.04, vscode, npm, bower, mean.io
* **ag-Grid-Enterprise version:** 2.0.X

ag-grid-enterprise v5.4.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by seanlandsman** [comment]
Hi

This is a good idea but unlikely to be something we will be able to get to anytime soon.

If you want full control over the filter you can use a Filter Component https://www.ag-grid.com/javascript-grid-filter-component

You can contact accounts@ag-grid.com however to try get this prioritised in our stack

thanks
