### ISSUE TITLE
Ag grid viewport with tree data

### ISSUE THREAD

**Issue by Vizer** [ceolter/ag-grid-enterprise#117]
Hello guys,
I am trying to implement viewport demo with tree data. Is it possible in current(or near future) implementation of ag-grid to have grouping functionality this way or it requires custom group cell renderer anyway?

Thanks

**Comment by seanlandsman** [comment]
Hi

The next release will offer support for server side grouping which should provide support for what you're after

**Comment by Vizer** [comment]
@seanlandsman, thanks for your answer. Could you tell me when I can expect next release?

**Comment by seanlandsman** [comment]
The next release is due out this week - thanks

**Comment by Vizer** [comment]
@seanlandsman, thank you for replay. I have checked out Enterprise Row Model and actually it does not solves my problem as I expected. It does not support partial rendering as viewport does and it does not support specific cell updating. Is it it still in development or maybe I have missed something?

P.S. viewport is exactly what I need but with addition of grouping
