### ISSUE TITLE
License warning in 9.0.0

### ISSUE THREAD

**Issue by jameswyse** [ceolter/ag-grid-enterprise#118]
Received the following warning after upgrading to 9.0.0 this morning:

<img width="1218" alt="screen shot 2017-03-30 at 9 16 46 am" src="https://cloud.githubusercontent.com/assets/1144357/24480922/92be1346-152a-11e7-96aa-f2893d6df688.png">

As far as I know our license is still valid so I'm assuming this is a bug?

**Comment by seanlandsman** [comment]
Hi

I've investigated and it looks like there is an issue there - I have fixed this and we'll do a patch release now.

Apologies for the inconvenience and thanks for letting us know

**Comment by seanlandsman** [comment]
Hi - 9.0.1 has been released to fix this issue.

thanks
