### ISSUE TITLE
set filter created, despite suppressFilters=true

### ISSUE THREAD

**Issue by sbublava** [ceolter/ag-grid-enterprise#121]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Assume a table that is defined like this:

    gridOptions = {
        enableFilter: true,
        rowModelType: 'infinite',
        columnDefs: [
            {
                suppressFilter: true
            }
        ]
    };

The console will be full of warnings:

ag-Grid: Set Filter cannot initialise because you are using a row model that does not contain all rows in the browser. Either use a different filter type, or configure Set Filter such that you provide it with values.

**Expected behavior**

Setting suppressFilter=true does not create a filter at all. If that is not feasible, please adjust the condition for the warning message.

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 9.0.1

* **Browser:** IE 11

* **Language:** TypeScript 2.2

**Comment by seanlandsman** [comment]
You can suppressFilter either on an individual column ( columnDef.suppressFilter ) or across all of them with 

gridOptions.defaultColDef: {
    suppressFilter
}

**Comment by sbublava** [comment]
Yes, but why does Ag-Grid create a filter instance at all, if columnDef.suppressFilter is set to true? That is the issue, especially since the filter instance it creates spams the console with bogus warnings.

**Comment by seanlandsman** [comment]
hi - if you can provide a plunker of the issue on the members forum I'd be happy to take a look at this for you. I'm sure we can work out why you're seeing what you're seeing 

thanks

**Comment by sbublava** [comment]
Hi!

Please have a look at http://plnkr.co/edit/PbT04MyV03Cq68nuEOWp, which reproduces the problem, once you enter a license key. (I should have provided this from the start.)

The key is setting floating filters to true. After that Ag-Grid writes this warning to the console:

ag-Grid: Set Filter cannot initialise because you are using a row model that does not contain all rows in the browser. Either use a different filter type, or configure Set Filter such that you provide it with values.

So it seems that floating filters somehow ignore the "suppressFilters" setting for the column.

Thanks,
Stephan

**Comment by tauqeer-qbatch** [comment]
IS there any solution? I am facing that same problem and I am unable to solve this issue.
