### ISSUE TITLE
Ecma 6 Object.values function breaks set filter

### ISSUE THREAD

**Issue by lvanderbijl** [ceolter/ag-grid-enterprise#124]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using the set filter with core-js polyfills the set filter doesn't enumerate all the available values for a column

The set filter currently uses the following code to determine whether it should use an existing list of values or enumerate the values from the grid data:
line 41: setFilterModel.ts
```
this.usingProvidedSet = Utils.exists(this.filterParams.values);
```

Because the core-js polyfills add a "values" function to the object prototype, the utils.exists method returns true when it should return false.

I did some further testing and either of the following 3 core-js polyfills break the set filter:
import 'core-js/es6/array';
import 'core-js/es6/map';
import 'core-js/es6/set';

These are all recommended by angular2 to support ie9, 10 and 11.

**Expected behavior**
The set filter should enumerate all values in a column

**Minimal reproduction of the problem with instructions**
Use the set filter with an ecma6 object.values polyfill

**What is the motivation / use case for changing the behavior?**
Ecma6

**Please tell us about your environment:**
win10, angular 2

* **ag-Grid-Enterprise version:** 9.0.3

* **Browser:** [Chrome XX ]

* **Language:** [ES5]
though my issue is with the es6 core.js polyfill

**Comment by lvanderbijl** [comment]
The only common module between the 3 core js polyfills is https://github.com/zloirock/core-js/blob/master/modules/es6.string.iterator.js.

But I can't see any thing there that would cause it to add the "values" function.

**Comment by seanlandsman** [comment]
Hi

Do you have a plunker or similar that we can take a look at for this?

thanks

**Comment by lvanderbijl** [comment]
I found the issue. The filter params was being set as an empty array in some custom code. 
Setting it correctly to an object resolved the issue.

Apologies for the distraction.

Thanks
