### ISSUE TITLE
Scrolling in IE11 is slow

### ISSUE THREAD

**Issue by Lucasvo1** [ceolter/ag-grid-enterprise#125]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Scrolling in IE11 is very slow. In Firefox and Chrome the scrolling is smooth but in IE11 there is some kind of delay when new rows are displayed. 

**Expected behavior**
The scrolling should be as smooth as in FF and Chrome since most of the people here use IE11

**Minimal reproduction of the problem with instructions**
Set up a grid with infinite scrolling with enough data

* **ag-Grid-Enterprise version:** 2.0.X
Enterprise version: 9.0.0
Ag-Grid-Angular: 9.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE 11

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by seanlandsman** [comment]
Hi

We've spent a lot of time around IE11 performance and I'm afraid there isn't much more we can do around this.

The best we can suggest is to use suppressScrollLag which will improve the user experience, but that's all I can suggest at this time I'm afraid

If you're an enterprise client feel free to log this in our Members Forum, but as I say I'm afraid we've probably gone as far as we can with IE11 scrolling performance.


thanks

**Comment by kirillonufreinko** [comment]
Could you please advice if moving to enterprise license could give us any additional chance to trigger work on IE performance?

**Comment by boreq** [comment]
The scrolling performance in IE11 is still abysmal. It is interesting that your solution to this problem in your so-called "enterprise" product involves closing the issue.
