### ISSUE TITLE
row group panel not visible with rowGroupPanelShow="always"

### ISSUE THREAD

**Issue by VyvIT** [ceolter/ag-grid-enterprise#128]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```
I'm evaluating ag-grid react with enterprise features based on [https://github.com/ceolter/ag-grid-react-example](url). 

**Current behavior**
Row group panel is not visible, though I see row group panel div rendered with 'ag-hidden' class.
If I remove class manually, I see panel with applied group
![image](https://user-images.githubusercontent.com/7152088/27340851-392b104a-55e4-11e7-8805-27e1bbdcf294.png)

**Expected behavior**
I expect row group panel to be visible.

**Minimal reproduction of the problem with instructions**
I've cloned https://github.com/ceolter/ag-grid-react-example.
I've npm installed ag-grid-enterprise and included ```import "ag-grid-enterprise";``` into index.js file.
Also in SimpleGridExample I've additionally added to enable showing row group panel:
```
                    <AgGridReact
                    // properties

                    columnDefs={this.state.columnDefs}
                    rowData={this.state.rowData}

                    // to enable grouping and show the grouping panel
                    rowGroupPanelShow="always"
                    defaultColDef={{
                      enableRowGroup: true,
                      enablePivot: true,
                      enableValue: true,
                    }}

                    // events
                    onGridReady={this.onGridReady}>
                </AgGridReact>
```
In Model column I chose 'Group by Model'.

**Please tell us about your environment:**
Win10

* **ag-Grid-Enterprise version:** 10.0.1
Tried on 9.1.0, 10.1.0 versions

* **Browser:** [all]
* **Language:** [ES6]

**Comment by seanlandsman** [comment]
Hi

This is a bug on our side - I've raised issue AG-557 for it and fixed it. It'll be available in our next release (to be released tomorrow, or early the following week)

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that as of 11.0.0 this has been implemented, see the changelog for more details..

https://www.ag-grid.com/change-log/changeLogIndex.php#gsc.tab=0
