### ISSUE TITLE
gridOptions.checkboxSelection not working as expected

### ISSUE THREAD

**Issue by gabrielenosso** [ceolter/ag-grid-enterprise#13]
Hi all!
Reading the doc I found out that gridOptions.checkboxSelection could be a function:
"gridOptions.checkboxSelection can also be specified as a function - use this if you want, for example, the first column to have checkbox selection regardless of which column it is (you would do this by looing at the params and returning true if colIndex = 0)."

If I pass something like "checkboxSelection: () => true" it should show the checkbox selection on each column, right?

I tried it with the ag-grid-react but it's not working...

**Comment by ceolter** [comment]
it should be a function, and nothing else!

i've just checked the code, it looks fine, and no changes there for months, so should be working, and has nothing to do with React.

you can take a look at the code, debug through the ag-Grid method calculateCheckboxSelection, see what the logic is doing with regard you settings. maybe it's reading something off the colDef (which gets preference if it's defined).

**Comment by mixail-novikov** [comment]
Based on changelog https://www.ag-grid.com/change-log/changeLogIndex.php

> gridOptions.checkboxSelection is now gone, use defaultColDef.checkboxSelection instead

Please, update documentation here https://www.ag-grid.com/javascript-grid-selection/, section "Checkbox Selection"
