### ISSUE TITLE
updateRowData addIndex not work

### ISSUE THREAD

**Issue by hksfho** [ceolter/ag-grid-enterprise#132]
* **ag-Grid-Enterprise version:**  11.0.0
* **Browser:** Chrome 59.0.3071.115
* **Language:** JavaScript, angular.js 1.6.5, jquery2.2.4

> 

`https://codepen.io/hksfho/pen/MozOPV/`

>  $scope.gridOptions.api.updateRowData({
      add: [{ id: 8888, name: "8888" }],
      addIndex: 1
    });

**Comment by seanlandsman** [comment]
Hi,

Add $scope.gridOptions.api.refreshInMemoryRowModel(); 

After $scope.gridOptions.api.updateRowData({

This will fix this for you.

It's worth noting however that the docs say:

" The index to add is put in for historical purposes and should not be used. If you want the grid to display in a certain order, you should apply a grid sort and have the row data sorted.""

thanks
