### ISSUE TITLE
Filter does not allow for complex objects using cellRendered values

### ISSUE THREAD

**Issue by swalters** [ceolter/ag-grid-enterprise#14]
see plunkr: https://plnkr.co/edit/3kLhFbPqUgWCzdVp9de1?p=preview

I have a complex field in my dataset that I need to keep as an object for the editor.  I can't set the .field to .person.first because I need the editor to have access to the entire person object. 

I use a cellRenderer to only render the first name.  I use the same cellRenderer for the filter.

The setFilterModel is converting the person object to a string [Object object]. the cellRenderer for the filter then receives param.value = [Object object] instead of the actual person object.

 private createAllUniqueValues() {
        if (this.usingProvidedSet) {
            this.allUniqueValues = _.toStrings(this.filterParams.values);
        } else {
            var uniqueValuesAsAnyObjects = this.getUniqueValues(false);
            **this.allUniqueValues = _.toStrings(uniqueValuesAsAnyObjects);**
        }

        this.sortValues(this.allUniqueValues);
    }

**Comment by ceolter** [comment]
the unique values have to be strings, as these end up as 'keys' in the map 'selectedValuesMap'

not a simple change. i'll think about it - see what i can come up with.

maybe we create the keys in another way, possibly have an optional callback where you can provide the key for an object.

i'd rather not move away from using a map with key/value pairs, as this is what allows the filter to work extremely fast.

**Comment by ceolter** [comment]
added 'keyCreator' to col def. it's a function that can return the key to use for the setFilter
