### ISSUE TITLE
Volatile Display on setRowData

### ISSUE THREAD

**Issue by JonahJ** [ceolter/ag-grid-enterprise#16]
Hey -

Using ag-grid and constantly replacing all rows with `setRowData` every few seconds as new data comes in. I understand it would be ideal and efficient to update rather than replace, but new rows are created and old ones are removed so may be more of a strain on the CPU. But if I'm wrong and there is a better way to do this, please let me know.

Anyway when I call `setRowData` the currently selected row and filtered column are reset. I'm getting around this with the following code (below), but we are experimenting with Ag-Grid Enterprise to see if we should buy and we wanted to know if there's a way to reexpand the expanded groups?

```
var selected_currently = $scope.gridOptions.api.getSelectedNodes()[0];
var previous_filter_model = $scope.gridOptions.api.getFilterModel();

$scope.gridOptions.api.setRowData(orders.get());

if (selected_currently) $scope.gridOptions.api.selectNode(selected_currently, true, true);
if (previous_filter_model) $scope.gridOptions.api.setFilterModel(previous_filter_model);
```

More specifically we would like the view after the call to `setRowData` to essentially be that of before, just with updated row data.

**Comment by ceolter** [comment]
```Using ag-grid and constantly replacing all rows with setRowData every few seconds as new data comes in. I understand it would be ideal and efficient to update rather than replace, but new rows are created and old ones are removed so may be more of a strain on the CPU. But if I'm wrong and there is a better way to do this, please let me know.```
=> if all the data is changing, then setRowData() is as fast as anything else, as you will end up redrawing the entire grid either way. if you are working with partial changes, you could consider using the viewport - I have no idea if it will fix your use case, that's for you to choose I guess.

with regards your selection question, are you asking if that will work? i don't think it will as the instances of the nodes will be different. what you need is a business key on your node, then look up the node that was selected last time.
```
var selectedNode = api.getSelectedNodes()[0];
api.setRowData(newData);
api.forEachNode( funcation(newNode) {
  if (newNode.data.businessKey === selectedNode.data.businessKey) {
    newNode.setSelected(true);
  }
}
```

**Comment by JonahJ** [comment]
Doing the above yields a `[$rootScope:inprog] $digest already in progress` error.

```
var selected_currently = $scope.gridOptions.api.getSelectedNodes()[0];
var previous_filter_model = $scope.gridOptions.api.getFilterModel();
var grouping_selected = $scope.gridOptions.api.onGroupExpandedOrCollapsed();

$scope.gridOptions.api.setRowData(orders.get());

if (selected_currently) $scope.gridOptions.api.forEachNode(function(node) {
      if(selected_currently.data._id == node.data._id) node.setSelected(true);
})
if (previous_filter_model) $scope.gridOptions.api.setFilterModel(previous_filter_model);
```

Error:
```
Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.5.5/$rootScope/inprog?p0=%24digest
at /_serveDev/code/libs/2.angular.js?ts=1462986869901&pathPrefix=libs:68:12
at beginPhase (/_serveDev/code/libs/2.angular.js?ts=1462986869901&pathPrefix=libs:17587:15)
at Scope.$digest (/_serveDev/code/libs/2.angular.js?ts=1462986869901&pathPrefix=libs:17025:9)
at Scope.$apply (/_serveDev/code/libs/2.angular.js?ts=1462986869901&pathPrefix=libs:17337:24)
at Object.$scope.gridOptions.onSelectionChanged (/_serveDev/code/app/controllers.js?ts=1462986869901&pathPrefix=app:355:18)
at GridOptionsWrapper.globalEventHandler (/_serveDev/code/libs/ag-grid-enterprise.js?ts=1462986869901&pathPrefix=libs:724:50)
at /_serveDev/code/libs/ag-grid-enterprise.js?ts=1462986869901&pathPrefix=libs:882:14
at Array.forEach (native)
at EventService.dispatchEvent (/_serveDev/code/libs/ag-grid-enterprise.js?ts=1462986869901&pathPrefix=libs:881:31)
at RowNode.setSelected (/_serveDev/code/libs/ag-grid-enterprise.js?ts=1462986869901&pathPrefix=libs:4929:36)
```

**Comment by ceolter** [comment]
ops, angular issue.

put this in a timeout:
```
if (selected_currently) $scope.gridOptions.api.forEachNode(function(node) {
      if(selected_currently.data._id == node.data._id) node.setSelected(true);
})
```
so something like
```
setTimeout( function() {
  if (selected_currently) $scope.gridOptions.api.forEachNode(function(node) {
      if(selected_currently.data._id == node.data._id) node.setSelected(true);
  })
}, 0);

**Comment by JonahJ** [comment]
Many thanks for that suggestion - just adjusted to do this. But the issue isn't the selected row, but the expanded grouping dropdowns. They automatically close after invoking `setRowData`. I can see them via `$scope.gridOptions.api.getRenderedNodes()`, with the `expanded` attribute. Maybe expand the `setExpanded` function that I can see internally. In meantime doing the following:

```
var expanded_groups = _.filter($scope.gridOptions.api.getRenderedNodes(), {
  expanded: true
});
var selected_currently = $scope.gridOptions.api.getSelectedNodes()[0];
var previous_filter_model = $scope.gridOptions.api.getFilterModel();

$scope.gridOptions.api.setRowData(orders.get());

if(expanded_groups.length) expanded_groups.forEach(function(grouping) {
  var live_group = _.filter($scope.gridOptions.api.getRenderedNodes(), {
    key: grouping.key
  })[0];

  live_group.expanded = true;
});
if (selected_currently && selected_currently.data) $scope.gridOptions.api.forEachNodeAfterFilterAndSort(function(node) {
  if(selected_currently.data._id == node.data._id) node.setSelected(true, true, true);
});
if (previous_filter_model) $scope.gridOptions.api.setFilterModel(previous_filter_model);
```

**Comment by ceolter** [comment]
use the grid property: rememberGroupStateWhenNewData

**Comment by Bhawna14** [comment]
Hi All,

i need some help for below issue..
i have scenarios where my grid should change data as per the response object.
i tried using this.gridOptions.api.setRowData(this.rowDataGrid); but i got a error as "Cannot read property 'setRowData' of undefined"
So i tried using 
this.gridOptions.api.setRowData(this.rowDataGrid);
        this.gridOptions = {
                  onGridReady: function() {
                     this.gridOptions.api.setRowData(this.rowDataGrid);
                  }
          }
with this i got error as "Cannot read property 'api' of undefined"


Please help i am very new to angular 2
