### ISSUE TITLE
Fix documentation of contextMenu

### ISSUE THREAD

**Issue by maxired** [ceolter/ag-grid-enterprise#2]
Hi.

Sorry, I am not sure about the best place to post this.
BTW, is there any repo/branch somewhere corresponding to the website ? 

On the page [grid-context-menu/index.php](https://www.ag-grid.com/angular-grid-context-menu/index.php) , you wrote

> `If you want to turn off the context menu completely, set the grid property suppressContextMenu=false.`

Actually it is the opposite, the `suppressContextMenu` attribute should be set to true to disable the context menu.

**Comment by ceolter** [comment]
thank you. i have fixed this. when i update the website again, it will be
changed.

the project for the docs is currently:
https://github.com/ceolter/ag-grid-docs

in the future i plan to break out the website core stuff from the docs. all
in good time.

**Comment by AmitMY** [comment]
@ceolter If this is fixed, how come is this not closed?
