### ISSUE TITLE
Dynamically refreshing all the data example

### ISSUE THREAD

**Issue by BuddyWork** [ceolter/ag-grid-enterprise#29]
I have a service that is publishing data to the Grid and would like to refresh all or specific rows, do you have an example that shows me how to do this?

Its a lovely grid by the way.

Sorry posted it to the wrong issue. Please close.

**Comment by AmitMY** [comment]
You have `refreshView()` for a full refresh
`refreshRows(rowNodes)` for specific rows
And `refreshCells(rowNodes, colIds)` for specific rows & columns
Here is the official page: `https://www.ag-grid.com/javascript-grid-refresh/index.php`

You also have `softRefreshView`, you should look into it
