### ISSUE TITLE
[Feature] suppressRowCopy

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid-enterprise#30]
When a cell is selected, and you press Ctrl + C, is copied to the clipboard.
When a row is selected, and also a cell is selected (maybe click, maybe arrow keys), and you press Ctrl + C, it will always copy the selected row.

Can you please add to the grid options: suppressRowCopy: Boolean (Default false)

(Added this here because the copy is an enterprise feature)

**Comment by ceolter** [comment]
will be in next release.
property is suppressCopyRowsToClipboard

**Comment by AmitMY** [comment]
Thanks a lot!

**Comment by brookpatten** [comment]
Exactly what I needed too, thanks!
