### ISSUE TITLE
[clibpboard] add additinoal settings to clipboard

### ISSUE THREAD

**Issue by JonahJ** [ceolter/ag-grid-enterprise#34]
Experimenting with the clipboard feature. Wondering if there are settings anywhere to specify things like:
- delimiter
- final formatting (ie cell formatting or raw)

**Comment by ceolter** [comment]
tracked by AG-182
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by hackhat** [comment]
@ceolter I can't find `AG-182` in https://www.ag-grid.com/ag-grid-pipeline/ . Also I wonder if is possible to have something like cellFormatters but for the copy cells. Thanks

**Comment by ceolter** [comment]
i can see 182 here
https://www.ag-grid.com/ag-grid-pipeline/

it's not done yet.

processCellForClipboard callback can be used for formatting before the cell hits the clipboard.

so only remaining item is to allow changing the deliminator.

**Comment by ceolter** [comment]
done. deliminator will be in next release.

**Comment by makinggoodsoftware** [comment]
Hi,

Just to let you know that as of 11.0.0 this has been implemented, see the changelog for more details..

https://www.ag-grid.com/change-log/changeLogIndex.php#gsc.tab=0
