### ISSUE TITLE
SHIFT selection doesn't include pinned columns.

### ISSUE THREAD

**Issue by pccjamie** [ceolter/ag-grid-enterprise#36]
Just installed version 5.0.0-alpha.3.  

I am able to SHIFT select multiple rows now. However, any columns that are pinned are not highlighted. That goes for columns that are pinned programmatically or by the user.

**Comment by ceolter** [comment]
thanks for raising. i'll give it a few hours, then release again. see if any other small items found. 

nothing to do with shift-select btw, just pinning and selection.

**Comment by pccjamie** [comment]
Thanks!
