### ISSUE TITLE
Context menu copy

### ISSUE THREAD

**Issue by sousarka** [ceolter/ag-grid-enterprise#37]
Hi,

Thank you for this excellent product. We're evaluating the enterprise version for the context-menu copy feature.

Is there any way to add callback before and after the context-menu "copy". Possible user-cases are:

-  provide my own formatted data to be copied to clipboard (not any cell, and not the entire row)

- show some notification that the text was copied to clipboard.

Also, It'd be nice to be able to have the ability to modify the context-copy label as well. ( e.g. "Copy Selected Users" etc.)

**Comment by ceolter** [comment]
you can put your own items into the menu. so just forget about the default 'copy' item - provide your own one called 'copy', and then you can use the grid API to call 'copyToClipboard' if you want (and do whatever you want before and after), or just copy whatever you want into the clipboard some other way!

**Comment by sousarka** [comment]
Thanks. 
I'd like to use the grid API copyToClipboard method, but there's no way I can provide my formatted data to it. Am I missing anything?
https://github.com/ceolter/ag-grid-enterprise/blob/master/src/clipboardService.ts#L163

I can try another library (Clipboard.js or zeroClipbpard.js) to copy data to clipboard if I can get hold of the menu element in some way.

**Comment by ceolter** [comment]
to format, use processCellForClipboard(params)
https://www.ag-grid.com/javascript-grid-callbacks/index.php

if you want to copy something other than the selected range, well that's up to you to provide that data.

**Comment by sousarka** [comment]
I think thats the one I was looking for. Thank you :+1:

**Comment by sousarka** [comment]
Getting an error on version 4.2.11

Uncaught TypeError: _grid.api.copyToClipboard is not a function
