### ISSUE TITLE
Inconsistent scrolling when columns are pinned

### ISSUE THREAD

**Issue by pccjamie** [ceolter/ag-grid-enterprise#38]
If I pin columns, and then scroll up and down when my cursor is hovering over any of the pinned columns, the rows redraw just fine. 

However if I scroll up and down when hovering over any UNpinned columns, there is a major lag in the redraw.  Here's a screenshot to show you what I mean:

<img width="1002" alt="screen shot 2016-07-01 at 10 57 51 am" src="https://cloud.githubusercontent.com/assets/569229/16525507/c02a4f7e-3f7a-11e6-916e-e186992d4edd.png">

**Comment by ceolter** [comment]
yes that's a performance issue i'm aware of. waiting for someone to suggest how to fix it! minor issue though.

**Comment by ceolter** [comment]
closing this as it's a general performance issue.

performance seems fine with Chrome, but not so good in IE.

**Comment by nikolasleblanc** [comment]
Possible to reopen this one? I'm seeing some considerable lag of the pinned column when scrolling above the non-pinned columns, but no lag of the non-pinned columns when scrolling above the pinned columns. I can see they're being handled by different event listeners, could it be that one is optimized and the other is less so?

**Comment by davidnormo** [comment]
I also am seeing this problem, would be great to know what's being done about it. Thanks

**Comment by sumcoding** [comment]
This is still an issue, not sure why it was ever closed as there does not seem to be a fix for it here. I would consider this a bug not a feature request.

**Comment by bmg-will** [comment]
Can confirm we are having this issue in Chrome every since upgrading to version 18.
