### ISSUE TITLE
max-height bug on ag-grid-enterprise

### ISSUE THREAD

**Issue by supersabillon** [ceolter/ag-grid-enterprise#41]
I posted about this bug on ag-grid: #https://github.com/ceolter/ag-grid/issues/849#event-706343732 

Apparently this only happens on enterprise.

Steps to reproduce:

- Set ag-grid to 100% height
- Set container div to max-height of 500px for example. 
- Issue is the last row of the grid is hidden and you need to scroll to see it.

Check out this jsfiddle to see an example: https://jsfiddle.net/zwh2oaLu/

**Comment by ceolter** [comment]
you are looking for auto-height of the grid, so it resizes to fit the rows. this is not supported by the grid. there is another issue open covering this.

**Comment by ceolter** [comment]
if you want to auto-size the grid, the only way to do it is to size the grid div manually, using maths, to work out how high it should be, given the rows you want to show.
