### ISSUE TITLE
Default cellRenderer for richSelect cell editor

### ISSUE THREAD

**Issue by jameswyse** [ceolter/ag-grid-enterprise#42]
I was having an issue where the `richSelect` cell editor wasn't rendering labels for the options in the virtual list. Each option was in the DOM and clickable but the `div.ag-rich-select-row` child was empty.

Adding a `cellRenderer` function to the `cellEditorParams` fixed the problem. Is this intentional or should it be falling back to the default renderer when not specified?

```javascript
cellEditor: 'richSelect',
cellEditorParams: {
    values: ['one', 'two'],
    cellRenderer: params => params.value // removing this line breaks the cellEditor
}
```

**Comment by ceolter** [comment]
ops! sorry. thanks for raising. fixed now. will be in next release.
