### ISSUE TITLE
bugs in deselectAll

### ISSUE THREAD

**Issue by dephiros** [ceolter/ag-grid-enterprise#44]
I am implementing a select all checkbox for the grid. When the checkbox is clicked, i either call gridOptions.api.selectAll() or gridOptions.api.deselectAll().

Version: ag-grid-enteprise 5.0.3
Steps to reproduce:
- enable grow grouping.
- calling selectAll will select the group rowNode
- call deselectAll will not deselect the group nodeRow

**Comment by ceolter** [comment]
fixed. will be in next release.
