### ISSUE TITLE
No way to access tool bar after resetting columns during aggregation

### ISSUE THREAD

**Issue by whittssg** [ceolter/ag-grid-enterprise#46]
Steps:

1. Open the tool bar
2. Choose Pivot mode
3. Check a column (for grouping)
4. Add a column to the values drag zone.
5. Close the toolbar
6. Click a column menu and select "reset columns"

After doing these steps there is no way to get back to the tool bar to disable pivoting - you have to refresh the browser. (unless you have you own dedicated toolpanel somewhere)

**Comment by ceolter** [comment]
fixed, will be in next release. now context menu will appear when you click on the body even when no rows are present.
