### ISSUE TITLE
Inconsistency in selection UI and model when paging

### ISSUE THREAD

**Issue by dephiros** [ceolter/ag-grid-enterprise#47]
Reproduce step:
- enable paging
- select 1 or more row from page 1
- go to page 2 then back to page 1
- UI shows no row is selected but gridApi.getSelectedNodes() returns selected rows

**Comment by ceolter** [comment]
fixed in release 5.1.x just released today.

you will need to implement getRowNodeId() function (have a look at the new virtual pagination examples, they use the getRowNodeId)

**Comment by dephiros** [comment]
@ceolter I implemented getRowNodeId() and gridApi.getSelectedNodes() seems to retain the node but the ui still does not show selection when paging.
I am using rowModel: 'pagination'. Is this only supposed to work with rowModel: 'virtual'?

**Comment by ceolter** [comment]
i only tested with virtual, it should in theory work with pagination also. let me test now....

**Comment by ceolter** [comment]
you were right, it wasn't working. i've it fixed now. will be in the next release.
