### ISSUE TITLE
Copy/Paste with checkboxselection=true

### ISSUE THREAD

**Issue by jbarber2016** [ceolter/ag-grid-enterprise#48]
We have checkboxselection=true and when the user checks a row, but then sometimes wants to copy a cell (other than the selected row) it only copies the selected row and not the cell the user chooses to copy.

**Comment by AmitMY** [comment]
I would recommend using this
```suppressCopyRowsToClipboard: true, // makes Ctrl+C copy cell, not row```
This makes the copy to be on the cell, and not full row, I think this is what you want, not sure

**Comment by jbarber2016** [comment]
Seems to work. Thanks for the suggestion

**Comment by ceolter** [comment]
thanks @AmitMY
