### ISSUE TITLE
filter set issues

### ISSUE THREAD

**Issue by jbarber2016** [ceolter/ag-grid-enterprise#49]
we enable filter sets.  One thing is the user will use the search textbox to filter the options, but the select all seems to only mean select all for everything even though the user has used the textbox to filter down the list of options.

**Comment by jbarber2016** [comment]
I just realized someone else posted this issue.

**Comment by ceolter** [comment]
correct, this is the expected behaviour. we do plan to revisit the set filter and allow both types (select all present vs select all). i'm guessing the other issue that raised this has the same comment as this. closing as duplicate.

**Comment by RefactorMan** [comment]
"select all present", does it exist already?
