### ISSUE TITLE
Menu icon override doesnt work

### ISSUE THREAD

**Issue by aditigoel23** [ceolter/ag-grid-enterprise#5]
If I provide an icon for "menu" under gridOptions.icons, the icon does show up correctly on hover over the column header. But when you click it and menu opens, the open menu shows the old icon.

**Comment by ceolter** [comment]
noted. the icons inside the enterprise menu are not currently changeable. will include this in an upcoming release.

**Comment by mpetkov** [comment]
Just to add to this, it would be a good idea to make all icons changeable.  There are also currently some icons in the ag-grid that are not changeable and load img files.  I made a fork for the the time being until it is resolved.

**Comment by JonahJ** [comment]
+1

**Comment by AmitMY** [comment]
I believe this was fixed a long long time ago
https://www.ag-grid.com/javascript-grid-icons/

**Comment by ceolter** [comment]
agreed, closing
