### ISSUE TITLE
refreshing data does not respond

### ISSUE THREAD

**Issue by pccjamie** [ceolter/ag-grid-enterprise#50]
Hello.  It seems that `refreshView()` is not working as documented. Nor is `softRefreshView()`, even when setting `volatile: true`.  

 I added loggers to the source code, and I can get into the related function calls, but nothing happens. And no errors are returned.

Uncertain whether I'm doing something wrong. I'm following the same pattern in our app for calling other grid api methods, all of which work fine. Just not refreshing data.  It takes a hard page reload to see the updated data in the grid.

**Comment by ceolter** [comment]
it does work, as demonstrated by the examples on this page:https://www.ag-grid.com/javascript-grid-refresh/index.php

so you have to be doing something wrong. if you can provide a plunker with the problem, someone can help troubleshoot???
