### ISSUE TITLE
Grid should use class instead of id for "north", "centerRow", "south" to easily support styling for multiple grids in the same page

### ISSUE THREAD

**Issue by dephiros** [ceolter/ag-grid-enterprise#51]

**Comment by ceolter** [comment]
you shouldn't be styling the north, centreRow etc, these are part of the grids border layout feature. what you should be styling is what is inside these containers, not the containers themselves.

however some people don't like using id's for layout - so i may change them to classes for that reason. however again i'd rather you didn't use them for your styling as they are not part of the documented interface and may change between releases.
