### ISSUE TITLE
"SetFilter" links to "SetFilterListItem" and doesn't have correct prototype (v5.0.6)

### ISSUE THREAD

**Issue by GAndriyS** [ceolter/ag-grid-enterprise#55]
agGrid.SetFilter links on SetFilterListItem, to reproduce this just console agGrid.SetFilter. Because of bad linking agGrid.SetFilter doesn't have correct prototype. So I have this issue with prototype, because I overwrite agGrid.SetFilter.prototype.createTemplate to set custom template for entire Set Filter.

**Comment by ceolter** [comment]
i use typescript to generate the javascript code, which in turn sets all this up. can you advise what is wrong in my typescript code?

i had a look, i don't see anything wrong, so i'm at the mercy of TypeScript generated code and Webpack here.

**Comment by GAndriyS** [comment]
Sorry for hard understandable question. In nutshell I need to set custom template for "Set Filter" and I used a bad way to do it. 
Can u please provide this feature?

**Comment by ceolter** [comment]
you should provide a cellRenderer, as explained here:
https://www.ag-grid.com/javascript-grid-set-filtering/index.php

it lots you render items in the list as you want.

**Comment by rkait** [comment]
@ceolter I found the line at which @GAndriyS was having the issue:
https://github.com/ceolter/ag-grid-enterprise/blob/master/src/clientExports.ts#L52
```javascript
exports.SetFilter = SetFilter;
exports.SetFilter = SetFilterListItem;
```
Seems that `SetFilterListItem` is being exported as and overriding `SetFilter`. Thanks for your help!

**Comment by rkait** [comment]
https://github.com/ceolter/ag-grid-enterprise/pull/76
