### ISSUE TITLE
How do you use ag-grid-enterpise with ag-grid-react?

### ISSUE THREAD

**Issue by nickytonline** [ceolter/ag-grid-enterprise#57]
Hi, I'm looking at `ag-grid-enterprise` for a project in the react ecosystem. `ag-grid-react` has a dependency on `ag-grid`. If I have `ag-grid-enterpise` installed `ag-grid-react` still references `ag-grid`. Maybe I'm missing an obvious step to get `ag-grid-react` to use `ag-grid-enterprise` or is there an enterprise version of `ag-grid-react`?

**Comment by ceolter** [comment]
just have your your project reference ag-grid-enterprise

eg
```
// only include this line if you want to use ag-grid-enterprise
require('ag-grid-enterprise');
```

the ag-grid-enterprise will install itself into ag-grid, so when you create a grid, it will have the enterprise features.
