### ISSUE TITLE
Question about grouping rows

### ISSUE THREAD

**Issue by nickytonline** [ceolter/ag-grid-enterprise#59]
Hi @ceolter. I'm doing some POCs and wondering if the following is possible out of the box/via custom renderer a custom renderer that is not hacky.

I need to be able to group by n number of columns. I can use the row grouping functionality from ag-grid-enterprise, https://www.ag-grid.com/javascript-grid-grouping, e.g.

```
+ col 1
|
+---- col 2
           | 
           +---- col 3
                        |
                        +---- col 4
                                      | ____ row (col1 data, col 2 data, col 3 data ...)

                                      |
                                      +------row (col1 data, col 2 data, col 3 data ...)
                                      ...
```
but the scenario I need is to have it group by these 4 columns and only have one collapsible row for the grouping, e.g.
```
+ Header row for col1 col2 col3 col 4
|____ row (col1 data, col 2 data, col 3 data ...)
|
+------row (col1 data, col 2 data, col 3 data ...)
...
```

I don't need the drill down. I was able to get something kind of working, but it seems hacky to me.

```
export class SomeGrid extends React.Component<ISomeGridProps, {}> {
  private api: ag.grid.GridApi;
  private columnApi: ag.grid.ColumnApi;
  private gridOptions: ag.grid.GridOptions;

  ...

  private onGridReady(params: any): void {
    this.api = params.api;
    this.columnApi = params.columnApi;
    this.api.setRowData(this.props.rowData);
  }

  private groupRowRenderer(params) {
    if (params.node.field === 'the_last_grouped_field') {
      return `<div>Some grouped row header</div>`;
    }

    return ''; // Don't want to create header rows for previously grouping.
  }

  private buildGridOptions(): ag.grid.GridOptions {
    const { rowData, columnDefinitions } = this.props;

    return ({
      rowData,
      columnDefs: columnDefinitions,
      groupUseEntireRow: true,
      groupDefaultExpanded: 4, // expand to the last group at the beginning.
      groupRowRenderer: this.groupRowRenderer
    });
  }

  ...
}
```

This works by using the `groupDefaultExpanded` grid option,  but the main problem is the rows are positioned absolutely using the row height, so even if I don't create a row in `groupRenderer`, I have a space even if the style is `display:none` for those header rows because each row's abosulute `top` is calculated as `top of last row + rowHeight`. So my final header ends up being 4 rows down leaving a gap. I thought if I could reset the counter that is calculating `top` for each row, I could get it to work, but once again this seems hacky and I also don't think you expose it.

Just wondering if you have any suggestions or if you could point me to somewhere in the docs if this functionality exists.

**Comment by ceolter** [comment]
if i understand your question correctly, then do not group by the 4 columns. instead create another column that has these 4 as a value.

eg suppose your 4 columns are:
```
colDef1 = {field: 'a', headerName: 'A'}
colDef2 = {field: 'b', headerName: 'B'}
colDef3 = {field: 'c', headerName: 'C'}
colDef4 = {field: 'd', headerName: 'D'}
```

then instead of the above, have this:
```
colDef1 = {valueGetter: 'data.a + data.b + data.c + data.d', headerName: 'ABCD'}
```

then group by colDef1.

you could be more creative with the valueGetter, instead of returning a string, you could return an object to represent the group:
```
colDef1 = {
  valueGetter: function(params) {
    return {
      a: params.data.a,
      b: params.data.b,
      c: params.data.c,
      d: params.data.d
    }
  }
}
```

then you would need to add a cellRenderer or a valueFormatter to present the object you return.

**Comment by nickytonline** [comment]
I should have drawn a bit more in my initial question. Here is the full scenario required. I need the individual column headers because some of the columns might have filtering/sorting.

```
|    Column 1 Header | Column 2 Header | Column 3 Header ...       |
--------------------------------------------------------------------
|    + Header Row for group by data                                |
|    |
|    | - Column 1 data     | Column 2 Data     | Column 3 Data ... |
|    |
|    |- Column 1 data     | Column 2 Data     | Column 3 Data  ... |
```

Is that possible without a lot of hacking like I mentioned before?

**Comment by ceolter** [comment]
then mix both - have the one column that i describe to do your grouping on, then also additionally have each of the 4 columns individually defined so you have the columns for your filtering.
