### ISSUE TITLE
is groupEntireRow broken ?

### ISSUE THREAD

**Issue by maxired** [ceolter/ag-grid-enterprise#6]
Hi,

I believe that there is a problem with the groupdEntireRow feature.

In the following exemple, https://jsfiddle.net/eafp3ye7/ , I can't find a way to hide the 'Make' columns
Looks like the behaviour changeed with the 4.0 refactoring.

Event Putting ` {headerName: "Make", field: "make", rowGroupIndex:0, width:-1}`  does not work because of default padding.

**Comment by ceolter** [comment]
to hide the column, put 'hide: true' on the column definition. or use the API to hide the column. setting width to -1 or 0 is not something the grid is designed for.
