### ISSUE TITLE
5.2.0: still got error for using forEachLeafNode with paging model

### ISSUE THREAD

**Issue by dephiros** [ceolter/ag-grid-enterprise#60]
I get "cannot call forEachNodeAfterFilter unless using normal row model"

**Comment by ceolter** [comment]
as per message, this is not available when using viewport or virtual pagination.

**Comment by dephiros** [comment]
Sorry I am still a bit confused. I am asking this question because of this sentence in the change log for 5.2.0:
> Enhancement: Allowed following methods to work with pagination: forEachLeafNode, forEachNodeAfterFilter, forEachNodeAfterFilterAndSort.

From what I understand, if i set rowModelType: 'pagination', I should be able to use forEachLeafNode?

**Comment by ceolter** [comment]
it works for normal pagination, but not virtual pagination.

i tested it with latest 5.3 (i just happen to have latest in my dev environment, no difference with this an 5.2 i believe). i took the first example on this page:
https://www.ag-grid.com/javascript-grid-pagination/index.php

and then added this bit:
```
setTimeout( function() {
    gridOptions.api.forEachLeafNode(function(node) {
        console.log('got node ' + node.data.athlete);
    });
}, 1000);
```

and it worked fine
