### ISSUE TITLE
Any way to not init ToolPanelComp?

### ISSUE THREAD

**Issue by billyvg** [ceolter/ag-grid-enterprise#61]
We are passing `showToolPanel: false`, but is there a way to completely disable it and not render/initialize at all? `ColumnSelectPanel` is causing very poor performance issues and since we don't use the tool panel, we would like to make sure it doesn't render at all.

Timeline:

![image](https://cloud.githubusercontent.com/assets/79684/17988982/d196f2fa-6ade-11e6-9a55-ba0eeedb38a0.png)

**Comment by ceolter** [comment]
what type of performance issues? i mean, are you talking milliseconds that are hardly noticeable, or seconds?

**Comment by billyvg** [comment]
It's significant, the screenshot I posted it from a 2015 MBP and it's 400ms

**Comment by ceolter** [comment]
i have now put lazy initialisation into the toolPanel. if not showing by default, it doesn't get initialised.

i tested this on the main demo page, and then show toolPanel in a timeout 1 second after page is shown. the time for the whole api.showToolPanel(true) to execute was 80ms. maybe i'm on a faster computer.
