### ISSUE TITLE
force column sorting

### ISSUE THREAD

**Issue by bwinchester** [ceolter/ag-grid-enterprise#62]
Is there anyway to sort/force the order that the columns are displayed? Using ag-grid enterprise in angular and I order the columns in the columnDefs array. Specifically I need a column with a field of '@timestamp' to be the first column in the table. I splice @timestamp's column def to index 0 of my column def array. 

The issue is that @timestamp always appears as the 2nd column, index 1. Just to try to fix it, I even added a .moveColumn() call into the onGridSizeChanged event. The column visibly moves back to the first item, and then about a second later, it moves back to the 2nd.

Back in ag-grid 4/x, column defs seemed to do just fine maintaining order.

Any ideas?

**Comment by ceolter** [comment]
the columns are displayed in the order you provide the columnDefs. this is what is happening in all the online demos. if this is not happening, well I don't know what is wrong. if you can reproduce in a plunker i can take a look?
