### ISSUE TITLE
Where is header row? (5.3.0)

### ISSUE THREAD

**Issue by rsmything** [ceolter/ag-grid-enterprise#63]
5.2.0
![image](https://cloud.githubusercontent.com/assets/11719983/18143210/868e8a10-6fda-11e6-92be-28cad287ab44.png)

5.3.0
![image](https://cloud.githubusercontent.com/assets/11719983/18143216/91b4588e-6fda-11e6-86a6-9fd6927a3b17.png)

How to fix it?)

**Comment by rsmything** [comment]
In version 5.3.0 the first row after setRowData() covers a row with column names.

**Comment by ceolter** [comment]
not in my examples. can you reproduce in a plunker?

my guess is some css in your app is conflicting with the grid's css.

**Comment by rsmything** [comment]
Thx, sorry, error in css, works after removed position: abxolute in .ag-header section
