### ISSUE TITLE
ag.grid.gridOptions deinfiton missing rememberGroupStateWhenNewData

### ISSUE THREAD

**Issue by nickytonline** [ceolter/ag-grid-enterprise#64]
Hi,

The grid options definition appears to be missing `rememberGroupStateWhenNewData: boolean;`. My guess is the definition is in the OSS version and that's why this is not included. Just a guess.

It's easy to circumvent, but I thought I would mention the issue anyways.

Here's the workaround for those in TypeScript land:
```
interface GridOptions extends ag.grid.GridOptions {
  rememberGroupStateWhenNewData: boolean;
}
```

**Comment by ceolter** [comment]
i see it here:
https://github.com/ceolter/ag-grid/blob/master/src/ts/entities/gridOptions.ts#L74

so it's not missing???

not sure why you see something different.

**Comment by nickytonline** [comment]
Weird, I'll make sure our d.ts is up to date. Thanks.
