### ISSUE TITLE
Filter request: Daterange

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid-enterprise#65]
Can you please add to your filters (not as a custom filter) a new filter called 'date', and (or just) 'daterange'.
This filter should allow to select a daterange or a single date, and then the filter will compare dates and show the relevant rows.

Here is one for the bootstrap grid:
http://www.daterangepicker.com/
I am not sure what you can use for the other templates.

Can you add this to your feature list?

This grid is great, and I think before you are developing new features for v6.0.0, you should really perfect the features that already exist.

**Comment by ceolter** [comment]
yes a date filter would be great. just need the time. thanks for raising.

**Comment by uguryilmaz** [comment]
that would be useful. waiting for it..

**Comment by ceolter** [comment]
last release now has date filtering.
