### ISSUE TITLE
Empty Context Menu

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid-enterprise#66]
If I have a grid with a few rows, plenty of empty space and right click in the empty space, it tries to open a context menu. A couple issues:
1) Should it even create a context menu when there's no row or column beneath?
2) If the develop returns an empty array of menu items, can the menu just not be displayed?

**Comment by ceolter** [comment]
1. yes, it should have the option to show the toolPanel. if this wasn't the case, then you would have no way of getting your columns back if you decided to make them all 'not visible'.

2. fair point. i've fixed this. now if no menu items are returned, the context menu is not shown.
