### ISSUE TITLE
Request: suppressToolPanel switch in gridOptions

### ISSUE THREAD

**Issue by robert-sutton** [ceolter/ag-grid-enterprise#68]
Our users have no use for the tool panel. The option in the context menu simply confuses them. If they click the option, the tool panel shows, and they are confused even more.

Can 'suppressToolPanel' be added to gridOptions? 
If true, the option simply does not appear in the context menu.

Thanks!

**Comment by ceolter** [comment]
you can already do this by overriding the context menu items

```
gridOptiosn.getContextMenuItems = function(params) {
  var result = params.defaultItems.splice(0);
  var index = result.indexOf("toolPanel");
  if (index >= 0) {
    result.splice(index, 1);
  }
  return result;
}
```

given you have this control, we don't want to add properties to gridoptions, as they would be unnecessary noise.
