### ISSUE TITLE
Can aggFunc help with this need?

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid-enterprise#71]
I have rows of data, looking like:
`{client: 1, deposit: {amount: 100, date: "2016-09-20 10:10:10"}}`
In my table, I show three columns:

- Client
- deposit.amount
- deposit.date

When grouping a client (client is groupable), I need to show the client's first deposit.
When doing aggFunc, I only get the amounts array, so I can't know which is the first.
Is there a way to get something like `aggFunc(rows)` instead of `aggFunc(values)`?

I asked this about 4 months ago, and you said no, because of pivot tables.

Can you think of a way to make this work naively? Doesn't have to be with aggFunc.. My only viable solution is creating a map of clients, then calculating the first deposit myself, and show it in a different column. Not to complex, O(n), but I would much prefer a native way, and using the same column (I = my bosses)

Thanks!

**Comment by ceolter** [comment]
if i understand this correctly, then the answer is pretty simple, you should use groupRowAggNodes, see it explained here:
https://www.ag-grid.com/javascript-grid-aggregation/index.php

this way you get the nodes to aggregate, and not the individual values.

**Comment by AmitMY** [comment]
Fantastic as always
Thanks!
