### ISSUE TITLE
Context Menu on Left Click

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid-enterprise#72]
You can call showColumnMenuAfterButtonClick to manually show the header. Can something similar be added for the context menu? My use case is I'd like for the context menu to show up when single left clicking some special cells.

```
$scope.onCellClicked = function (cell) {
    if (!cell.node.floating) {
        return;
    }

    //@ todo Show context menu here
};
```

**Comment by randdusing** [comment]
It was actually pretty simple after taking another look at the source. I basically just need to obtain the RenderedCell object and then I can manually call the contextMenu event.

Perhaps there's a better way to get the RenderedCell from the params? This method is a bit hacky since I'm making assumptions about the node being within the bottom floating rows.

```
onCellClicked: function (params) {
    if (!params.node.floating) {
        return;
    }

    var renderedRows = params.api.rowRenderer.renderedBottomFloatingRows;
    var row = renderedRows[params.rowIndex];
    var cell = row.renderedCells[params.colDef.field];

    cell.onContextMenu(params.event);
}
```

**Comment by ceolter** [comment]
sorry for delay, last while has been very busy. wow - what you are doing is defiantly a hack! a good one though, it will work. are you in London and looking for a job by any chance???

there is no other way to show the context menu via the API :(

**Comment by randdusing** [comment]
No worries! I'm from Houston, Texas, but quite happy with my current gig.

**Comment by ceolter** [comment]
I should of guessed Texas with your profile pic and the hat!!

**Comment by kishore-dumpa** [comment]
@randdusing 
I'm able to get the context menu '**onCellFocused**'
How can I close the context menu forcefully any Idea?

**Comment by randdusing** [comment]
Not sure off the top of my head, but if you take a look at the source code, you can probably figure out a way.

**Comment by namnn** [comment]
I think the onCellClicked param has changed and there's no way to obtain CellComp object from this param.

I went through the code and seems that we can manually trigger the context menu via onMouseEvent() of CellComp class. But how can I get there inside onCellClicked callback?

Thanks in advance.

**Comment by namnn** [comment]
@umanglani brilliant hack, thank you

**Comment by louMoxy** [comment]
Having the same issue as @namnn, any chance of providing a getter for rowRenderer? 

Also seems the api has changed so new hack is: 

```
(params: CellClickedEvent): void => {

  const {rowIndex, node, column, event, value} = params;

  const cell = params.api.rowRenderer.rowCompsByIndex[rowIndex].getRenderedCellForColumn(column);

  cell.beans.contextMenuFactory.showMenu(node, column, value, event);
};
```

**Comment by Isrolik-MorYosef** [comment]
> Having the same issue as @namnn, any chance of providing a getter for rowRenderer?
> 
> Also seems the api has changed so new hack is:
> 
> ```
> (params: CellClickedEvent): void => {
> 
>   const {rowIndex, node, column, event, value} = params;
> 
>   const cell = params.api.rowRenderer.rowCompsByIndex[rowIndex].getRenderedCellForColumn(column);
> 
>   cell.beans.contextMenuFactory.showMenu(node, column, value, event);
> };
> ```
 
I did what you wrote, it works great!  He just put an error on rowRenderer because it's private.  Is there a way to handle this?

**Comment by penx** [comment]
```js
var gridOptions = { 
 ... 
 onCellClicked: params => {  
   params.api.contextMenuFactory.showMenu(
      params.node, 
      params.column, 
      params.value,   
      params.event
   )
 },
}
```

https://ag-grid.zendesk.com/hc/en-us/articles/360020272191-Trigger-context-menu-with-left-click

**Comment by ryancwalsh** [comment]
@penx Thank you so much! I forked it to https://plnkr.co/edit/juqmkY75POgHm6wv which will probably work for my use case.
