### ISSUE TITLE
suppressCopy

### ISSUE THREAD

**Issue by randdusing** [ceolter/ag-grid-enterprise#74]
I know 5.4 allows you to specify which columns to copy when using copySelectedRowsToClipboard, but could this also be configurable from the column definition? If using the built in copy context menu item, this would come in handy.

**Comment by ceolter** [comment]
this isn't needed - you can replace the context menu item with our own item that would then call grid api with the columns you want.

i did think about implementing this, but then stood back as i shouldn't be putting something in to the grid that only 1% of users will use, especially if there is a workaround.

**Comment by randdusing** [comment]
That makes sense. I'll try that out

**Comment by nasaleanhorea** [comment]
It sill doesn't fix the issue when using CTRL + C from the keyboard - which a lot of users actually use for copy. I tried returning undefined / false on processCellForClipboard() but it still creates and empty cell when pasting to Excel.
