### ISSUE TITLE
export CSV onlySelected with paging

### ISSUE THREAD

**Issue by dephiros** [ceolter/ag-grid-enterprise#75]
I am using ag-grid with rowModelType: "pagination"
When selecting two rows in page1 and then selecting three rows in page2:
Expected:
- gridApi.getSelectedRows returns 5 rows
- exportDataAsCsv({onlySelected: true}) return 5 rows
Current Behavior:
- gridApi.getSelectedRows returns 5 rows
- exportDataAsCsv({onlySelected: true}) return 3 rows(page2)

Would love for exportDataAsCsv to return 5 rows. If not, at the very least i think those call should be consistent in their behavior

**Comment by ceolter** [comment]
done. added property onlySelectedAllPages to do this - i didn't want to change what was there, it has it's uses.
