### ISSUE TITLE
Incorrect indeterminate state of Select All checkbox in Set FIlter

### ISSUE THREAD

**Issue by GAndriyS** [ceolter/ag-grid-enterprise#78]
Example grid: https://www.ag-grid.com/javascript-grid-set-filtering/exampleSetFilter.html
Steps to reproduce:
1) Deselect all Years
2) Select any
3) Deselect selected
Result: Select All checkbox still has indeterminate state

**Comment by ceolter** [comment]
thanks for raising, will look into it.

**Comment by ceolter** [comment]
fixed, will be in tomorrows release.
