### ISSUE TITLE
Client sort/Filtering on full loaded rows in virtual scrolling

### ISSUE THREAD

**Issue by spoonkeeper** [ceolter/ag-grid-enterprise#79]
Hi,
We're moving towards an enterprise license for a solution we're developing, and I already have a question/feature request
When in virtual row model, we filter/sort on our server but it takes longer than in the browser given network latency and I wondered if it is possible to automatically switch on client filtering/sorting when all rows have been loaded for small collections (ie max page cache count > current page cache count and last row is known)
Thank you for your response and great lib btw

**Comment by ceolter** [comment]
not possible. selecting the row model is something that is done while the gird is created, you cannot change it after that. if you did want to do what you say, then you can destroy the grid and create a new one with the standard row model - but you will have to move the rows into this yourself, its not something we try and do out of the box.
