### ISSUE TITLE
[filter set] filter menu not updating when data is changed

### ISSUE THREAD

**Issue by IS-smcleod** [ceolter/ag-grid-enterprise#8]
I have a grid for users to review old sets of data.  When switching between sets, the filter options do not change to match.  Not sure if I need to call anything in addition to setRowData() to make that happen.

**Comment by AmitMY** [comment]
@IS-smcleod I know this is a very old issue, but any chance for a plunkr?

**Comment by ceolter** [comment]
tracked by AG-185
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
We don't seem to be able to reproduce this issue, when we tried in our end we swap the data that the grid is showing and every time we did through gridOptions.api.setRowData() the set filters automatically got updated with the new values.

Can you make sure that you are not providing a hardcoded list of values to be used in the column definition? If you still experience the issue, please let us know

**Comment by IS-smcleod** [comment]
Sorry I missed the notification for the other messages.  I checked the original place where this was causing and issue and it is no longer doing that.  It doesn't use a hardcoded list. I haven't updated any code for those pages since update I have been updating the library so I'm not sure how or when it was fixed.

**Comment by nite** [comment]
Note this is happening again in ag-grid 19.0.0 - using `setRowData()`
