### ISSUE TITLE
reload the grid but keep the current page

### ISSUE THREAD

**Issue by dephiros** [ceolter/ag-grid-enterprise#81]
Right now I am having two different use case of reloading the data of the grid. One is satisfied by gridApi.setDataSource(dataSource) which reload the data and reset the page. Is there a way to reload the data of the current page?

**Comment by ceolter** [comment]
not now, but it's on our plan. we plan to refactor the pagination panel, which will include providing an API to do all of this sort of stuff. there is already an issue open for this so closing this one (regardless, it's on our private planner here). we expect to get it done before end of this year.
