### ISSUE TITLE
[webpack] Trouble getting alias for ag-grid-root working with webpack and eslintrc

### ISSUE THREAD

**Issue by dharric** [ceolter/ag-grid-enterprise#82]
Basically getting errors like unable to resolve path to module 'ag-grid-root...'. I've tried a couple of configs but cannot get it to work.
This is my current eslintrc entry

```
settings: {
  'import/resolver': {
    webpack: 'webpack.config.prod.js'
  }
}
```

Then in my webpack file

```
resolve: {
  root: path.resolve(__dirname),
  alias: {
    "ag-grid-root": __dirname + "/node_modules/ag-grid"
  }
}
```

**Comment by ceolter** [comment]
i am not a Webpack expert, I just know enough to get ag-Grid working. how the packaging is done in ag-Grid is explained here:
https://www.ag-grid.com/understanding-packaging-for-javascript-typescript-commonjs-and-everything-else/

unless anyone else viewing can give Webpack advice???

**Comment by seanlandsman** [comment]
@dharric have you resolved this? what errors are you seeing?

**Comment by seanlandsman** [comment]
Closing as more information required
