### ISSUE TITLE
e.iterateObject in Enterprise version tries to perform one iteration on empty arrays

### ISSUE THREAD

**Issue by matthewjalder** [ceolter/ag-grid-enterprise#85]
e.iterateObject in Enterprise version tries to perform one iteration on empty arrays which breaks auto-sizing if any of the three inputs are empty (renderedRows, renderedBottomFloatingRows or renderedTopFloatingRows) as it tries to call getCellForCol on the wrong object (as a result of the spurious iteration).

I think the missing check should be missingOrEmpty, not just missing?

**Comment by ceolter** [comment]
how do you reproduce this?

**Comment by ceolter** [comment]
no feedback, closing
