### ISSUE TITLE
Listen to table scroll

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid-enterprise#89]
Is there a callback for listening to scroll?
In v5 I used `isScrollLag` for it, I know its not it's purpose.
Couldn't find anything in the documentation

**Comment by AmitMY** [comment]
Current "solution" is using:
`onViewportChanged: scrollingHandler`

Not a 100% scrolling events, but for some needs is usable

**Comment by ceolter** [comment]
event you want is ```bodyScroll```

**Comment by AmitMY** [comment]
Thanks @ceolter !
It is not documented in [events](https://www.ag-grid.com/javascript-grid-events/)

**Comment by ceolter** [comment]
that's because it's a secret. don't tell anyone.

**Comment by AmitMY** [comment]
LOL I won't. Thanks

**Comment by ceolter** [comment]
btw, you in israel right? i didn't see you at Angular UP two weeks ago!

**Comment by AmitMY** [comment]
I am
I was not aware of the event, or who was attending 
I would have definitely attended if I knew you were going!

Well, I guess next time

**Comment by ceolter** [comment]
yea next time, was all a bit of a rush. we were actually sponsoring it.
http://angular-up.com/

**Comment by AmitMY** [comment]
Damn. I wish I knew sooner

Hope Israel made a good impression on you.

I didn't know ag-grid grew so big to sponsor such events, that is awesome!

I don't usually attend these kind of events, for no particular reason except for laziness perhaps.
I will start.. tomorrow :)

**Comment by ceolter** [comment]
that was one of the smaller ones, we also sponsored Angular Connect in London and ng-Europe in Paris this year, next year we are already signed up to ng-Conf https://www.ng-conf.org/sponsors/

**Comment by AmitMY** [comment]
Thanks!
Don't know if I have the money/time to got to the US in the middle of a school year, I will look for more local stuff

I am now subscribed to the newsletter, so if there will be something more local I will be updated and go

**Comment by aknimmag** [comment]
Hello Everyone, 

Thank you so much for sharing the info about **bodyScroll** event.

But it is returning the scroll pointer position, is there any event that is fired when the user scrolls **to the end of the grid**? (Just to load more data by triggering a service call)

My Tech Stack: Typescript

Thanks in advance.

**Comment by ilyaskarim** [comment]
The secret bodyScroll has been added lol!

**Comment by anilkumarmv** [comment]
onBodyScroll event is not firing an event when table is scrolled.
gridOptions.onBodyScroll = this.getSelectedGroupItems()
Is their any other way to know that table is scrolled
