### ISSUE TITLE
Width responsiveness

### ISSUE THREAD

**Issue by gabrielenosso** [ceolter/ag-grid-enterprise#9]
Is there a way to let the grid have a responsive width?

Probably is the same thing requested here: https://github.com/ceolter/ag-grid/issues/412

And in some way it could also be connected to this: https://github.com/ceolter/ag-grid/issues/627

**Comment by ceolter** [comment]
nope, because of how the grid works, it uses columns and a horizontal scroll, the column widths are not related to the grid width, unless you choose 'sizeColumnsToFit()'
