### ISSUE TITLE
Copying cell value to clipboard doesn't work when range selection is disabled.

### ISSUE THREAD

**Issue by SoyYoRafa** [ceolter/ag-grid-enterprise#91]
I haven't tried pasting.

**Comment by ceolter** [comment]
i've added this to my list to look into.

the logic is that it copies the selected range. when you click on a cell, that is actually creating a range selection of once cell, hence it works.

**Comment by ceolter** [comment]
this is now fixed, will be in next weeks release. if no range or selected rows, then the focused cell will get copied.
