### ISSUE TITLE
RowNode.children attribute missing for group nodes

### ISSUE THREAD

**Issue by sousarka** [ceolter/ag-grid-enterprise#92]
The RowModel document says children attribute is present for group nodes, but I dont see any children attribute in the group RowNode.

![groupnode](https://cloud.githubusercontent.com/assets/6607561/20944269/f86f8680-bbbf-11e6-882e-41ab159122cb.PNG)

**Comment by ceolter** [comment]
see the attribute in this class:
https://github.com/ceolter/ag-grid/blob/master/src/ts/entities/rowNode.ts

the docs were wrong, i'll fix them (will be in the next release)
