### ISSUE TITLE
Unable to select empty value in richSelect

### ISSUE THREAD

**Issue by xwb1989** [ceolter/ag-grid-enterprise#95]
When using the richSelect editor, there is no way to input an 'empty value'

For example, with the following config:

```
cellEditor: 'richSelect',
cellEditorParams: {values: ['', 'true', 'false']}
```
when editing the cell, there are indeed 3 options appearing in the list, however, the first one, which is empty, is not clickable and therefore cannot be selected.

This problem does not appear with 'select' editor.

**Comment by ceolter** [comment]
fixed. will be in next release.
