### ISSUE TITLE
When focus cell is copied, processCellForClipboard return value is not used

### ISSUE THREAD

**Issue by dokokano-panda** [ceolter/ag-grid-enterprise#96]
When focus cell is copied, processCellForClipboard return value is not used.
I confirmed the code, but I think the following is incorrect.

https://github.com/ceolter/ag-grid-enterprise/blob/master/src/clipboardService.ts#L304

current:
var data = value.toString();

correctly:
var data = processedValue.toString();

**Comment by ceolter** [comment]
thanks. fixed.
https://github.com/ceolter/ag-grid-enterprise/commit/2595e169898af2ace50d7376f6364f6ab9e964a2

will be in next release.

**Comment by dokokano-panda** [comment]
thanks!
