### ISSUE TITLE
weird column filter behavior after switching to enterprise

### ISSUE THREAD

**Issue by squarewave24** [ceolter/ag-grid-enterprise#97]
the free version column filter works amazingly, one click and start typing/filtering. 

after switching to enterprise, the filter textbox is filtering only the contents of it's own dropdown, not the grid. 

http://i.imgur.com/GdNfl2Q.png

hitting enter does nothing. the only way i can even get it to work is to first uncheck all, then type the filter, and then check it. it's like 5 step process.  

how can i get the filter to start filtering grid immediately

```
<ag-grid-ng2 #agGrid style="width: 100%; height: 86%" class="ag-etp"

    [gridOptions]="gridOptions"
    [columnDefs]="columnDefs"
    [showToolPanel]="showToolPanel"
    [rowData]="Products"

    enableColResize
    enableSorting
    enableFilter

    rowHeight="20"
    rowSelection="multiple"
    >
</ag-grid-ng2>
```

**Comment by ceolter** [comment]
the default filter type is different for enterprise.

if you want the default filter to be text (and not set), set it as a column property in the col def, ie put the filter='text'

**Comment by squarewave24** [comment]
thanks, that worked. 

I have to say that the default behavior seems useless. it filters out options to filter, so you can't even change them since they are hidden in the list (but still not hidden in the grid). can't think of a case where this would be desired behavior.
